#! /bin/sh
set -e
touch config.h.in pinconfig.h.in
libtoolize --ltdl --force
[ -e config.h.in ] || touch config.h.in
autoheader
aclocal
automake --add-missing

autoconf
autoheader
./configure

echo "# ./configure && make && make install"
