#! /bin/sh

set -e
set -x

rm -rf libltdl

touch config.h.in pinconfig.h.in
ln -fs README.md README

libtoolize --version
aclocal --version
autoheader --version 
automake --version
autoconf --version

libtoolize --ltdl --force --copy
[ -e config.h.in ] || touch config.h.in

aclocal
autoheader
automake --add-missing
autoconf

echo "# $0 && ./configure && make && make install && src/pinball"
