/* pinconfig.h.  Generated by configure.  */
/* pinconfig.h.in.  Generated from configure.ac by autoheader.  */

/* The data dir /usr/local/share/pinball */
#define EM_DATADIR "/usr/local/share/pinball"

/* Shall we use debug features such as profiling and keyboard ball steering */
/* #undef EM_DEBUG */

/* Highscore directory */
#define EM_HIGHSCORE_DIR "/var/games/pinball"

/* The library or plugin dir /usr/local/lib/pinball */
#define EM_LIBDIR "/usr/local/lib/pinball"

/* Shall we compile unittests */
/* #undef EM_UNIT_TEST */

/* Shall we use allegro - software rendering */
/* #undef EM_USE_ALLEGRO */

/* Quadtree instead of octtree */
#define EM_USE_QUADTREE 1

/* Shall we use SDL and OpenGL */
#define EM_USE_SDL 1

/* One color per vertex */
#define EM_USE_SHARED_COLOR 1

/* Specular */
#define EM_USE_SOURCE_SPECULAR 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "pinball"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "henqvist@users.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pinball"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pinball 0.3.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pinball"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.3.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.3.1"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */
